# Generated by Django 4.0.4 on 2022-10-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=100)),
                ('hotel_city', models.CharField(max_length=100)),
                ('managers_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_rooms', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('hotel_info_slug', models.SlugField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Family', 'Family'), ('Luxary', 'Luxary')])),
            ],
        ),
    ]
