# Generated by Django 4.1.2 on 2022-10-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merostay_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_info',
            name='room_type',
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='double_room',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='family_room',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='luxary_room',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='single_room',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
