# Generated by Django 4.1.2 on 2022-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merostay_api', '0003_remove_hotel_info_hotel_info_slug_hotel_info_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_info',
            name='double_room',
        ),
        migrations.RemoveField(
            model_name='hotel_info',
            name='family_room',
        ),
        migrations.RemoveField(
            model_name='hotel_info',
            name='luxary_room',
        ),
        migrations.RemoveField(
            model_name='hotel_info',
            name='single_room',
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='double_room_price',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='family_room_price',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='luxary_room_price',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='single_room_price',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='total_double_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='total_family_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='total_luxary_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='total_single_room',
            field=models.IntegerField(default=0),
        ),
    ]
