# Generated by Django 4.1.2 on 2022-11-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merostay_api', '0004_remove_hotel_info_double_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_info',
            name='balcony_room',
            field=models.BooleanField(default=False, verbose_name='balcony_room'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='coffe_maker_service',
            field=models.BooleanField(default=False, verbose_name='coffe_maker'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='full_time_service',
            field=models.BooleanField(default=False, verbose_name='24/7_service'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='laundary_service',
            field=models.BooleanField(default=False, verbose_name='laundary_service'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='property_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Hostel/PG', 'Hostel/PG')], default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='resturant',
            field=models.BooleanField(default=False, verbose_name='resturant'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='smoking_room',
            field=models.BooleanField(default=False, verbose_name='smoking_room'),
        ),
        migrations.AddField(
            model_name='hotel_info',
            name='tv_room',
            field=models.BooleanField(default=False, verbose_name='tv_room'),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='hotel_city',
            field=models.CharField(blank=True, choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Chitwan', 'Chitwan'), ('Nagarkot', 'Nagarkot'), ('Pokhara', 'Pokhara'), ('Butwal', 'Butwal')], max_length=20, null=True),
        ),
    ]
